server:
  port: 9998
  #配置web页面入口
magic-api:
  web: /magic/web
  #配置文件存储位置。当以classpath开头时，为只读模式
  resource:
    location: /Users/stopping/data/magic-api
  response-code:
    success: 200 #执行成功的code值
    invalid: 400 #参数验证未通过的code值
    exception: 500 #执行出现异常的code值
# 连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.242.44:4001/magic-api-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xdp123456