spring:
  redis:
    host: 120.24.242.44
    port: 60001
    password: xdp123456
    database: 0
    jedis:
      pool:
        max-active: 32
        max-idle: 4
        max-wait: 3000
        min-idle: 0