spring:
  datasource:
    test-database:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_database?useUnicode=true&useSSL=false&&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: xdp123456
    user-database:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_database?useUnicode=true&useSSL=false&&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: xdp123456