spring:
  datasource:
    test:
      driverClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ideamake-test.mysql.rds.aliyuncs.com:3306/ideamake_mc?useUnicode=true&useSSL=false&&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: ideamake_dbuser
      password: 1a!gHco@d2mrgf^*^4lwGpB^
      hikari:
        max-lifetime: 1800000
    user:
      driverClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ideamake-test.mysql.rds.aliyuncs.com:3306/ideamake_zeus?useUnicode=true&useSSL=false&&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: ideamake_dbuser
      password: 1a!gHco@d2mrgf^*^4lwGpB^
server:
  port: 8080

feign:
  user:
    url: xxx
    name: zzz